In [ ]:
import numpy as np

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
t.dim()

1

In [ ]:
t.shape

torch.Size([7])

In [ ]:
t.size()

torch.Size([7])

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
t.dim()

2

In [ ]:
t.size()

torch.Size([4, 3])

In [ ]:
print(t[:, 1])

tensor([ 2.,  5.,  8., 11.])


In [ ]:
print(t[:, 1].size())

torch.Size([4])


In [ ]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])

In [ ]:
a = m1 + m2

In [ ]:
a.shape

torch.Size([1, 2])

In [ ]:
a.size()

torch.Size([1, 2])

In [ ]:
a

tensor([[5., 5.]])

In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t.shape

torch.Size([2])

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
t.mean(dim=0)

tensor([2., 3.])

In [ ]:
t = torch.FloatTensor([[10, 2], [3, 4]])
print(t)

tensor([[10.,  2.],
        [ 3.,  4.]])


In [ ]:
t.max(dim=1)

torch.return_types.max(values=tensor([10.,  4.]), indices=tensor([0, 1]))

In [ ]:
t = [[[0, 1, 2],
      [3, 4, 5]],
     [[6, 7, 8],
      [9, 10, 11]]]
ft = torch.FloatTensor(t)

In [ ]:
ft.size()

torch.Size([2, 2, 3])

In [ ]:
ft.view(-1,2,3)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft)

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])


In [ ]:
print(ft.squeeze_())
print(ft)

tensor([0., 1., 2.])
tensor([0., 1., 2.])


In [ ]:
ft.unsqueeze(0)

tensor([[0., 1., 2.]])

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [ ]:
print(torch.cat([x,y]))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
print(torch.cat([x,y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [ ]:
print(torch.cat([x, y, z]))

tensor([1., 4., 2., 5., 3., 6.])


In [ ]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])

In [ ]:
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [ ]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
x

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
x.mul_(2)

tensor([[ 8., 16.],
        [24., 32.]])

In [ ]:
x

tensor([[2., 4.],
        [6., 8.]])

In [ ]:
import torch

In [ ]:
a = 0
b = 0

In [ ]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


In [ ]:
class calculator:
  def __init__(self):
    self.result = 0
  
  def add(self, num):
    self.result += num
    return self.result

In [ ]:
cal1 = calculator()

In [ ]:
cal1.add(1)

2