## 1) 선형 회귀

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [ ]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [ ]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [ ]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [ ]:
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
optimizer = optim.SGD([W, b], lr=0.01)
# 학습 대상인 W와 b가 SGD의 입력이 됨.

In [ ]:
optimizer.zero_grad()
cost.backward()
optimizer.step()
#하강법 최적화 함수 opimizer의 .step() 함수를 호출하여 
#인수로 들어갔던 W와 b에서 리턴되는 변수들의 기울기에 학습률(learining rate) 0.01을 
#곱하여 빼줌으로서 업데이트합니다.

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

num_epochs = 1999
for epoch in range(num_epochs + 1):
  # H(x) 계산
  hypothesis = x_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad() # 미분을 통해 얻은 기울기를 0으로 초기화합니다.
  cost.backward() # 비용 함수를 미분하여 gradient 계산
  optimizer.step() #위 backward를 통해 x - x*lr 로 경사하강법 실행
  #경사 하강법은 비용 함수를 미분하여 이 함수의 기울기(gradient)를 구해서 비용이 최소화 되는 방향을 찾아내는 알고리즘

  # 100번마다 로그 출력
  if epoch % 100 == 0:
      print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
          epoch, num_epochs, W.item(), b.item(), cost.item()
      ))


Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [ ]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


## 2) 자동 미분

In [ ]:
import torch

In [ ]:
w = torch.tensor(2.0, requires_grad=True)

In [ ]:
y = w**2
z = 2*y + 5

In [ ]:
z.backward()

In [ ]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


## 3) 다중 선형 회귀

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)
num_epochs = 1000

for epoch in range(num_epochs + 1):
   hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
   cost = torch.mean((hypothesis - y_train)**2)

   optimizer.zero_grad()
   cost.backward()
   optimizer.step()

   if epoch % 100 == 0:
     print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
          epoch, num_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
      ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_train)
print(y_train)

torch.Size([5, 3])
torch.Size([5, 1])
tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  80.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [ ]:
w = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
hypothesis = x_train.matmul(w) + b

In [ ]:
optimizer = optim.SGD([w, b], lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(w) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))


Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

## 4) nn.Module로 구현하는 선형 회귀
* 이전 까진 가설함수 / 비용함수를 직접 정의해서 구현했찌만, 파이토치 모델을 이용해서 쉽게 구현이 가능함

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
model = nn.Linear(1,1)

In [ ]:
print(list(model.parameters()))
# 첫번째 값이 W / 두번째 값이 b => 두 값모두 랜덤으로 초기화 되어있음.

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
num_epochs = 2000
for epoch in range(num_epochs+1):
  pred = model(x_train)
  cost =F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, num_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
new_var = torch.FloatTensor([4])
pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값 : ", pred_y)

훈련 후 입력이 4일 때의 예측값 :  tensor([7.9989], grad_fn=<AddBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
model = nn.Linear(3,1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091429
Epoch  500/2000 Cost: 4.831834
Epoch  600/2000 Cost: 4.585997
Epoch  700/2000 Cost: 4.353045
Epoch  800/2000 Cost: 4.132426
Epoch  900/2000 Cost: 3.923438
Epoch 1000/2000 Cost: 3.725488
Epoch 1100/2000 Cost: 3.537972
Epoch 1200/2000 Cost: 3.360339
Epoch 1300/2000 Cost: 3.192076
Epoch 1400/2000 Cost: 3.032686
Epoch 1500/2000 Cost: 2.881703
Epoch 1600/2000 Cost: 2.738666
Epoch 1700/2000 Cost: 2.603199
Epoch 1800/2000 Cost: 2.474860
Epoch 1900/2000 Cost: 2.353289
Epoch 2000/2000 Cost: 2.238115


In [ ]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.7184]], grad_fn=<AddmmBackward>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


## 5) 클래스로 파이토치 모델 구현하기

In [ ]:
model = nn.Linear(1,1)

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self): # init에서 모델의 구조와 동적을 정의하는 생성자를 정의
    super().__init__() # nn.Module의 속성을 갖게 됨
    self.linear = nn.Linear(1, 1)

  def forward(self, x): # model객체를 데이터와 함께 호출하면 자동으로 실행 됨
    return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
model = nn.Linear(3, 1)

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()

In [ ]:
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [ ]:
num_epochs = 2000
for epoch in range(num_epochs + 1):
  pred = model(x_train)
  cost = F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print("Epoch {:4d}/{} Cost:{:6f}".format(epoch, num_epochs, cost.item()))

Epoch    0/2000 Cost:18.562185
Epoch  100/2000 Cost:0.128051
Epoch  200/2000 Cost:0.079128
Epoch  300/2000 Cost:0.048896
Epoch  400/2000 Cost:0.030215
Epoch  500/2000 Cost:0.018671
Epoch  600/2000 Cost:0.011538
Epoch  700/2000 Cost:0.007129
Epoch  800/2000 Cost:0.004406
Epoch  900/2000 Cost:0.002722
Epoch 1000/2000 Cost:0.001682
Epoch 1100/2000 Cost:0.001040
Epoch 1200/2000 Cost:0.000642
Epoch 1300/2000 Cost:0.000397
Epoch 1400/2000 Cost:0.000245
Epoch 1500/2000 Cost:0.000152
Epoch 1600/2000 Cost:0.000094
Epoch 1700/2000 Cost:0.000058
Epoch 1800/2000 Cost:0.000036
Epoch 1900/2000 Cost:0.000022
Epoch 2000/2000 Cost:0.000014


In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
num_epochs = 2000
for epoch in range(num_epochs + 1):
  pred = model(x_train)
  cost = F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print("Epoch {:4d}/{} Cost:{:6f}".format(epoch, num_epochs, cost.item()))

Epoch    0/2000 Cost:11517.784180
Epoch  100/2000 Cost:1.542943
Epoch  200/2000 Cost:1.483091
Epoch  300/2000 Cost:1.426335
Epoch  400/2000 Cost:1.372504
Epoch  500/2000 Cost:1.321457
Epoch  600/2000 Cost:1.273041
Epoch  700/2000 Cost:1.227105
Epoch  800/2000 Cost:1.183562
Epoch  900/2000 Cost:1.142241
Epoch 1000/2000 Cost:1.103038
Epoch 1100/2000 Cost:1.065842
Epoch 1200/2000 Cost:1.030547
Epoch 1300/2000 Cost:0.997054
Epoch 1400/2000 Cost:0.965277
Epoch 1500/2000 Cost:0.935116
Epoch 1600/2000 Cost:0.906485
Epoch 1700/2000 Cost:0.879303
Epoch 1800/2000 Cost:0.853507
Epoch 1900/2000 Cost:0.829003
Epoch 2000/2000 Cost:0.805743


### 6) 미니 배치와 데이터 로드

In [46]:
from torch.utils.data import TensorDataset
# TensorDataset은 기본적으로 텐서를 입력으로 받음
from torch.utils.data import DataLoader

In [5]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [6]:
dataset = TensorDataset(x_train, y_train)

In [11]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [9]:
model = nn.Linear(3, 1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [19]:
num_epochs = 20
for epoch in range(num_epochs + 1):
  for batch_index, samples in enumerate(dataloader):
    x_train, y_train = samples
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, num_epochs, batch_index+1, len(dataloader),
        cost.item()))

Epoch    0/20 Batch 1/3 Cost: 1624.044556
Epoch    0/20 Batch 2/3 Cost: 689.449280
Epoch    0/20 Batch 3/3 Cost: 266.390961
Epoch    1/20 Batch 1/3 Cost: 50.107334
Epoch    1/20 Batch 2/3 Cost: 11.838553
Epoch    1/20 Batch 3/3 Cost: 3.348348
Epoch    2/20 Batch 1/3 Cost: 3.330845
Epoch    2/20 Batch 2/3 Cost: 0.016328
Epoch    2/20 Batch 3/3 Cost: 0.885240
Epoch    3/20 Batch 1/3 Cost: 0.535603
Epoch    3/20 Batch 2/3 Cost: 0.196102
Epoch    3/20 Batch 3/3 Cost: 0.758034
Epoch    4/20 Batch 1/3 Cost: 0.921633
Epoch    4/20 Batch 2/3 Cost: 0.323351
Epoch    4/20 Batch 3/3 Cost: 0.098794
Epoch    5/20 Batch 1/3 Cost: 0.268220
Epoch    5/20 Batch 2/3 Cost: 0.632139
Epoch    5/20 Batch 3/3 Cost: 0.134312
Epoch    6/20 Batch 1/3 Cost: 0.226473
Epoch    6/20 Batch 2/3 Cost: 0.318450
Epoch    6/20 Batch 3/3 Cost: 0.878563
Epoch    7/20 Batch 1/3 Cost: 0.766053
Epoch    7/20 Batch 2/3 Cost: 0.296484
Epoch    7/20 Batch 3/3 Cost: 0.629187
Epoch    8/20 Batch 1/3 Cost: 0.348614
Epoch    8/20 Ba

In [21]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.3520]], grad_fn=<AddmmBackward>)


### 07) 커스텀 데이터셋

In [47]:
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [48]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [49]:
model = torch.nn.Linear(3, 1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [50]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 48189.210938
Epoch    0/20 Batch 2/3 Cost: 6344.856445
Epoch    0/20 Batch 3/3 Cost: 4219.934082
Epoch    1/20 Batch 1/3 Cost: 1232.357422
Epoch    1/20 Batch 2/3 Cost: 211.230530
Epoch    1/20 Batch 3/3 Cost: 94.851654
Epoch    2/20 Batch 1/3 Cost: 35.020794
Epoch    2/20 Batch 2/3 Cost: 12.516342
Epoch    2/20 Batch 3/3 Cost: 1.705835
Epoch    3/20 Batch 1/3 Cost: 5.902531
Epoch    3/20 Batch 2/3 Cost: 1.409709
Epoch    3/20 Batch 3/3 Cost: 0.105256
Epoch    4/20 Batch 1/3 Cost: 1.801692
Epoch    4/20 Batch 2/3 Cost: 5.859886
Epoch    4/20 Batch 3/3 Cost: 0.013233
Epoch    5/20 Batch 1/3 Cost: 2.745019
Epoch    5/20 Batch 2/3 Cost: 1.258049
Epoch    5/20 Batch 3/3 Cost: 6.271763
Epoch    6/20 Batch 1/3 Cost: 2.508431
Epoch    6/20 Batch 2/3 Cost: 4.365737
Epoch    6/20 Batch 3/3 Cost: 0.000443
Epoch    7/20 Batch 1/3 Cost: 0.327389
Epoch    7/20 Batch 2/3 Cost: 3.066322
Epoch    7/20 Batch 3/3 Cost: 8.057867
Epoch    8/20 Batch 1/3 Cost: 2.089079
Epoch  

In [51]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.8098]], grad_fn=<AddmmBackward>)
