### 1) 순환 신경망(Recurrent Neural Network, RNN)
* 시퀀스 모델로서 입력과 출력을 시퀀스 단위로 처리하는 모델
* 셀(cell) : 은닉층에서 활성화 함수를 통해 결과를 내보내는 역할 / 이전값을 기억하려는 메모리 역할을 수행함

은닉층 : ht=tanh(Wx xt+Wh ht−1+b)
출력층 : yt=f(Wy ht+b)

* 

In [ ]:
#의사 코드
hidden_state_t = 0
for input_t in input_length:
  output_t = tanh(input_t, hidden_state_t)
  hidden_state_t = output_t

In [ ]:
import numpy as np

timesteps = 10 #시점의 수, NLP에서는 문장의 길이
input_size = 4 # 입력의 차원, NLP에서는 단어 벡터의 차원
hidden_size = 8 # 은닉 상태의 크기(메모리 셀의 용량)

inputs = np.random.random((timesteps, input_size))

hidden_state_t = np.zeros((hidden_size,))

In [ ]:
np.random.random(4).shape

(4,)

In [ ]:
Wx

array([[0.97968166, 0.72725146, 0.93801963, 0.01387884],
       [0.15587539, 0.88199314, 0.66294721, 0.21336194],
       [0.17424269, 0.02470587, 0.25510299, 0.19862745],
       [0.47405695, 0.827071  , 0.38921874, 0.93855581],
       [0.38610743, 0.38915661, 0.07707707, 0.37268734],
       [0.77719763, 0.81266665, 0.29985709, 0.38939602],
       [0.24363848, 0.09324648, 0.62365332, 0.8211618 ],
       [0.49460033, 0.26308494, 0.3326483 , 0.49930757]])

In [ ]:
inputs[0]

array([0.102464  , 0.34305758, 0.18879346, 0.94482337])

In [ ]:
Wx.shape

(8, 4)

In [ ]:
inputs[0].shape

(4,)

In [ ]:
print(hidden_state_t)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np.dot(Wx,np.random.random((4)))

array([0.65803546, 0.64295676, 0.07453373, 0.6107845 , 0.28193523,
       0.59893529, 0.19508372, 0.2607204 ])

In [ ]:
Wx = np.random.random((hidden_size, input_size))  # (8, 4)크기의 2D 텐서 생성. 입력에 대한 가중치.
Wh = np.random.random((hidden_size, hidden_size)) # (8, 8)크기의 2D 텐서 생성. 은닉 상태에 대한 가중치.
b = np.random.random((hidden_size,)) 

In [ ]:
print(np.shape(Wx))
print(np.shape(Wh))
print(np.shape(b))

(8, 4)
(8, 8)
(8,)


In [ ]:
total_hidden_states = []

for input_t in inputs:
  output_t = np.tanh(np.dot(Wx, input_t) + np.dot(Wh, hidden_state_t) + b)
  total_hidden_states.append(list(output_t))
  print(np.shape(total_hidden_states))
  hidden_state_t = output_t

total_hidden_states = np.stack(total_hidden_states, axis = 0) 

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)


In [ ]:
total_hidden_states

array([[0.9746737 , 0.91628689, 0.70170562, 0.97790403, 0.72849026,
        0.98053736, 0.78484936, 0.75619013],
       [0.99984168, 0.9982045 , 0.99906932, 0.99946091, 0.99807719,
        0.99998842, 0.99810434, 0.99913079],
       [0.99996609, 0.99978026, 0.99977278, 0.99987735, 0.99913579,
        0.99999733, 0.99946205, 0.9998156 ],
       [0.99989688, 0.99960921, 0.99973369, 0.99975485, 0.99869213,
        0.99999353, 0.9992844 , 0.99970337],
       [0.99996814, 0.9993776 , 0.99979521, 0.99964015, 0.99876037,
        0.99999526, 0.99939885, 0.99980214],
       [0.99998697, 0.99989457, 0.99986574, 0.9999788 , 0.99958108,
        0.99999903, 0.99990089, 0.99994018],
       [0.99999054, 0.99987998, 0.99986747, 0.9999536 , 0.99939552,
        0.99999856, 0.99987229, 0.99992376],
       [0.99997432, 0.99973669, 0.99985857, 0.99995512, 0.99943937,
        0.99999816, 0.99987831, 0.9999251 ],
       [0.99998378, 0.99988632, 0.9998385 , 0.9999715 , 0.99954614,
        0.99999897, 0.999825

In [ ]:
import torch
import torch.nn as nn

In [ ]:
input_size = 5
hidden_size = 8

In [ ]:
inputs = torch.Tensor(1, 10, 5)
inputs

tensor([[[-6.4732e-03,  3.0920e-41, -1.3420e-01,  4.2109e-02, -7.0839e-02],
         [-6.4201e-02,  3.0594e-01, -9.9273e-02, -3.0487e-01, -3.0922e-01],
         [-2.8605e-01,  1.6000e-01,  2.5849e-01, -1.4544e-01, -1.0939e-02],
         [-2.0929e-01,  3.2932e-01, -3.0837e-01, -9.3404e-02, -3.4039e-01],
         [ 2.2851e-01,  1.4310e-01, -2.1912e-02, -3.2560e-01, -2.5621e-01],
         [ 2.2226e-01, -9.3973e-02, -3.1237e-01, -1.5862e-01, -1.6572e-01],
         [ 3.2052e-01,  3.3894e-01, -1.4035e-01,  2.2878e-01,  1.1248e-01],
         [ 1.6952e-01, -3.0717e-01,  1.9994e-01,  1.2238e-02,  3.0337e-01],
         [-2.4321e-01, -1.3822e-01,  5.9962e-04,  2.5619e-01,  1.1312e-01],
         [ 2.5395e-01, -2.9191e-01,  1.0091e-01,  3.1288e-01, -3.1037e-01]]])

In [ ]:
cell = nn.RNN(input_size, hidden_size, batch_first=True)

In [ ]:
outputs, _status = cell(inputs)

In [ ]:
print(outputs.shape) 

torch.Size([1, 10, 8])


In [ ]:
print(_status.shape) # 최종 time-step의 hidden_state

torch.Size([1, 1, 8])


In [ ]:
inputs = torch.Tensor(1, 10, 5)

In [ ]:
cell = nn.RNN(input_size=5, hidden_size=8, num_layers=2, batch_first=True)

In [ ]:
outputs, _status = cell(inputs)

In [ ]:
print(outputs.shape)

torch.Size([1, 10, 8])


In [ ]:
print(_status.shape) # (층의 개수, 배치 크기, 은닉 상태의 크기)

torch.Size([2, 1, 8])


In [ ]:
_status

tensor([[[-0.4076,  0.4974,  0.6555,  0.2135,  0.3700,  0.3465, -0.1443,
           0.5489]],

        [[-0.5214,  0.7077, -0.3616,  0.4296, -0.6698, -0.7014,  0.1605,
          -0.5797]]], grad_fn=<StackBackward>)

In [ ]:
outputs

tensor([[[-0.2717,  0.5234, -0.2261,  0.4416, -0.2488, -0.4501, -0.0093,
          -0.5013],
         [-0.3377,  0.7085, -0.3590,  0.4971, -0.5804, -0.5839,  0.2328,
          -0.5831],
         [-0.5005,  0.7110, -0.3125,  0.4913, -0.7116, -0.6703,  0.1865,
          -0.5886],
         [-0.5541,  0.7335, -0.3354,  0.4488, -0.6601, -0.7393,  0.2214,
          -0.5611],
         [-0.5292,  0.7045, -0.3377,  0.4616, -0.7266, -0.6915,  0.1895,
          -0.5558],
         [-0.5412,  0.7125, -0.3504,  0.4236, -0.6963, -0.7187,  0.1416,
          -0.5750],
         [-0.5694,  0.7155, -0.3303,  0.4597, -0.6961, -0.7142,  0.1895,
          -0.5691],
         [-0.5589,  0.7200, -0.2974,  0.4590, -0.6604, -0.7387,  0.2058,
          -0.5411],
         [-0.5111,  0.6892, -0.2852,  0.4879, -0.7079, -0.6750,  0.1676,
          -0.5300],
         [-0.5214,  0.7077, -0.3616,  0.4296, -0.6698, -0.7014,  0.1605,
          -0.5797]]], grad_fn=<TransposeBackward1>)

In [ ]:
inputs = torch.Tensor(1, 10, 5)

In [ ]:
cell = nn.RNN(input_size = 5, hidden_size = 8, num_layers = 2, batch_first=True, bidirectional = True)

In [ ]:
outputs, _status = cell(inputs)

In [ ]:
print(outputs.shape) 

torch.Size([1, 10, 16])


In [ ]:
print(_status.shape) 

torch.Size([4, 1, 8])


### 2) 장단기 메모리(Long Short-Term Memory, LSTM)
* 바닐라RNN은 짧은 시퀀스에 대해서만 효과를 보임
* timestamp가 길어질수록 앞의 정보가 전달되지 못함
* LSTM은 셍 상태(cell state)라는 값을 추가함 (닉 상태값과 셀 상태값을 구하기 위해서 새로 추가 된 3개의 게이트를 사용)

##### (1) 입력 게이트
* 입력게이트는 현재 정보를 기억하기 위한 게이트

it = σ(Wxi xt+Whi ht−1+bi)
gt = tanh(Wxg xt+Whg ht−1+bg)
* 시그모이드 함수를 지나 0과 1 사이의 값과 하이퍼볼릭탄젠트 함수를 지나 -1과 1사이의 값 두 개가 나오게 됨
* 이 두 값을 통해 이번에 선택된 기억할 정보의 양을 정함
##### (2) 삭제 게이트
* 삭제 게이트는 기억을 삭제하기 위한 게이트

ft = σ(Wxf xt+Whf ht−1+bf)
* 현재시점 t의 x값과 이전 시점 t-1의 은닉상태가 시그모이드 함수를 지남
* 시그모이드 함수를 지나면서 0과 1 사이의 값이나옴
* 이 값은 삭제과정을 거친 정보의 양임 ( 0ㅇ에 가까울수록 정보가 많이 삭제 된 것이고 1에 가까울수록 온전히 기억한 것)

##### (3) 셀 상태(장기 상태)
* 셀 상태 Ct를 LSTM에서는 장기 상태라고 부르기도 함

Ct = ft∘Ct−1+it∘gt
* 입력 게이트에서 구한 it, gt 이 두 개의 값에 대해서 원소별 곱을 진행(두 행렬이 있을 때 같은 위치의 성분끼리 곱하는 것)
* 입력 게이트에서 선택된 기억을 삭제 게이트의 결과값과 더함
* 이 값을 현재 시점 t의 셀 상태(이 값은 다음 t+1 시점의 LSTM 셀로 넘겨짐)

삭제 게이트와 입력 게이트의 영향력을 이해해봅시다.
*  삭제 게이트의 출력값인 ft
가 0이 된다면, 이전 시점의 셀 상태값인 Ct−1
은 현재 시점의 셀 상태값을 결정하기 위한 영향력이 0이 되면서, 오직 입력 게이트의 결과만이 현재 시점의 셀 상태값 Ct
을 결정할 수 있음 (이는 삭제 게이트가 완전히 닫히고 입력 게이트를 연 상태를 의미)
*  반대로 입력 게이트의 it값을 0이라고 한다면, 현재 시점의 셀 상태값 Ct
는 오직 이전 시점의 셀 상태값 Ct−1
의 값에만 의존함 (이는 입력 게이트를 완전히 닫고 삭제 게이트만을 연 상태를 의미함)
* => 결과적으로 삭제 게이트는 이전 시점의 입력을 얼마나 반영할지를 의미하고, 입력 게이트는 현재 시점의 입력을 얼마나 반영할지를 결정함

##### (4) 출력게티트와 은닉 상태(단기 상태)
* 출력 게이트는 현재 시점 t의 x값과 이전 시점 t-1의 은닉 상태가 시그모이드 함수를 지난 값임 (해당 값은 현재 시점 t의 은닉 상태를 결정하는 일에 쓰이게 됨)

ot = σ(Wxo xt+Who ht−1+bo)
ht = ot∘tanh(ct)
* 단기 상태의 값은 또한 출력층으로도 향함

In [1]:
import torch
import torch.nn as nn

In [ ]:
nn.RNN(input_dim, hidden_size, batch_first)

In [ ]:
nn.LSTM(input_dim, hidden_size, batch_first)